// Discovery surfaces: OpenAI's /v1/models, the custom /capabilities
// introspection endpoint, and the Ollama probes a daemon-aware client sends
// before it will list a server's Models. Every response here is derived
// from the loaded config (src/config.ts) and the Backend registry
// (src/backends/index.ts) at request time — nothing is hardcoded, so a
// Model added to models.json shows up with no code change.

import { models, type ModelConfig } from "./config.ts";
import { backends } from "./backends/index.ts";

// Stamped once at process start; used as a stand-in "created"/"modified"
// time since Models have no real creation timestamp of their own.
const startedAt = Math.floor(Date.now() / 1000);
const startedAtIso = new Date(startedAt * 1000).toISOString();

// ---- GET /v1/models -------------------------------------------------------

export type OpenAIModel = {
  id: string;
  object: "model";
  created: number;
  owned_by: string;
};

export function listOpenAIModels(): { object: "list"; data: OpenAIModel[] } {
  const data: OpenAIModel[] = Object.entries(models).map(([id, cfg]) => ({
    id,
    object: "model",
    created: startedAt,
    owned_by: cfg.backend,
  }));
  return { object: "list", data };
}

// ---- GET /capabilities -----------------------------------------------------

// The request fields the chat-completions endpoint actually reads (see
// ChatCompletionRequest in src/openai.ts). Every Model is served by the same
// HTTP surface, so this list is uniform across Models; anything else an
// OpenAI client sends (temperature, top_p, max_tokens, ...) is accepted but
// ignored.
const ACCEPTED_OPTIONS = ["model", "messages", "stream"] as const;

export type ModelCapability = {
  id: string;
  backend: string;
  llm: string;
  streaming: boolean;
  tools: false;
  options: readonly string[];
};

export function listCapabilities(): { object: "list"; data: ModelCapability[] } {
  const data: ModelCapability[] = Object.entries(models).map(([id, cfg]) => {
    const backend = backends[cfg.backend];
    return {
      id,
      backend: cfg.backend,
      llm: cfg.model,
      // Read off the Backend, never inferred from its name — a Backend with
      // streaming:false (e.g. a future codex Backend) must fall out of this
      // generically.
      streaming: backend?.streaming ?? false,
      tools: false,
      options: ACCEPTED_OPTIONS,
    };
  });
  return { object: "list", data };
}

// ---- Ollama discovery probes ----------------------------------------------
//
// Just enough of Ollama's response shapes for an Ollama-aware client to
// recognise a live daemon and enumerate Models. /api/chat is intentionally
// not implemented (see issue #3) — Ollama's chat wire format is
// newline-delimited JSON, not the SSE this server already speaks for
// /v1/chat/completions, and no client has needed it yet.

export const OLLAMA_ROOT_MESSAGE = "Ollama is running";

export function ollamaVersion(): { version: string } {
  return { version: "0.0.0-localAIWrapper" };
}

type OllamaModelDetails = {
  parent_model: string;
  format: string;
  family: string;
  families: string[];
  parameter_size: string;
  quantization_level: string;
};

function ollamaDetails(cfg: ModelConfig): OllamaModelDetails {
  return {
    parent_model: "",
    format: "gguf",
    family: cfg.backend,
    families: [cfg.backend],
    parameter_size: cfg.model,
    quantization_level: "unknown",
  };
}

type OllamaTagEntry = {
  name: string;
  model: string;
  modified_at: string;
  size: number;
  digest: string;
  details: OllamaModelDetails;
};

export function ollamaTags(): { models: OllamaTagEntry[] } {
  return {
    models: Object.entries(models).map(([id, cfg]) => ({
      name: id,
      model: id,
      modified_at: startedAtIso,
      size: 0,
      digest: "",
      details: ollamaDetails(cfg),
    })),
  };
}

export function ollamaShow(name: string): Record<string, unknown> | undefined {
  const cfg = models[name];
  if (!cfg) return undefined;

  return {
    modelfile: `# generated by localAIWrapper\n# backend: ${cfg.backend}\n# model: ${cfg.model}`,
    parameters: "",
    template: "",
    details: ollamaDetails(cfg),
    model_info: {
      "general.architecture": cfg.backend,
      "general.basename": cfg.model,
    },
  };
}
